### [Interface]
# Название WireGuard интерфейса
# Это имя будет использоваться для идентификации интерфейса в системе
wireguard_name_vpn_interface: wg-vpn

# IP-адрес WireGuard интерфейса, в формате IP/маска подсети
wireguard_address_interface: 10.10.8.2/32

### [Peers]
# Подсети, которые будут доступны через VPN-соединение
# Эти подсети определяют, какой трафик будет направляться через туннель WireGuard
wireguard_allowed_ips:
  # Подсеть самого WireGuard интерфейса
  # Включение этой подсети позволит VPN-клиентам видеть друг друга
  # Примечание: даже если эта подсеть не указана, другие сети все равно смогут использовать VPN
  - 10.10.8.0/24

  # Дополнительные разрешенные подсети, доступные через VPN
  # Примечание: подсети должны быть указанны с протиположной стороны
  - 192.168.99.0/24
  - 192.168.10.0/24

# Endpoint сервера-респондента (ответчика) WireGuard
# Здесь указывается IP-адрес сервера и порт, на котором он слушает
# Значение берется из inventory
wireguard_respondent_endpoint: "{{ hostvars[groups['respondent_vpn_server'][0]].ansible_host }}:{{ wireguard_listen_port }}"
#
# Интервал отправки пакетов для поддержания соединения (в секундах)
# Раскомментируйте эту строку, если wireguard_respondent_endpoint закомментирован
# Это помогает поддерживать соединение активным, особенно при использовании NAT
# wireguard_persistent_keepalive: 25

